### ISSUE TITLE
Create "file upload" capability for cf-checker process

### ISSUE THREAD

**Issue by agstephens** [cedadev/pyramid-phoenix#2]
We need to add upload capability for use by compliance checkers (such as the cf-checker).

This would appear in the form for a process. 

The user could provide one input as an uploaded file. 

Then maybe it gets remembered as a URL that the WPS can then download the file from when attempting to access it as an input.

**Comment by agstephens** [comment]
On JASMIN we might do:
- user uploads file to WPS UI
- WPS UI saves it to shared GWS
- WPS UI registers it as a URL input
- WPS service receives the URL as one of its inputs
- If WPS service recognises it is a local URL:
   - it reads it as a local file (i.e. on the GWS)
- Else:
   - it downloads it to a cache and then reads it

**Comment by antony-wilson** [comment]
See commits 381df6961fe98879bc9bb7e47f62b495479caf3c and add6e8d54440df87a3f9a0ccc52dac9c29073d25

In order to do a file upload use is made of the deform `FileUploadWidget`.

For the FileUploadWidget you must implement a FileUploadTempStore. These commits include an implementation of the `FileUploadTempStore` that writes the file to disk.
The root used for the path to write the files is taken from the configuration variable `file-upload-storage-dir`. 
The limit of the file size that can be uploaded is set by the configuration variable `file-upload-max-size-mb`

The current implementation of the `FileUploadWidget` returns a string that is the path to the uploaded file. This needs updating to be a URL.

**Comment by antony-wilson** [comment]
The file upload widget now returns a URL rather than a directory path.

There is still an issue with the widget. When a form containing the widget is submitted and there is an error in one of the other fields, the form is reloaded and it appears that the uploaded file is no longer there, but it is.

**Comment by agstephens** [comment]
@antony-wilson can we close this one?
